name: 'jest-coverage'
on:
  pull_request:
    branches:
      - develop
      - main
jobs:
  coverage:
    env:
      ADP_TOKEN: ${{ secrets.ADP_TOKEN }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    permissions:
      checks: write
      pull-requests: write
      contents: read
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          version: latest
      - uses: ArtiomTr/jest-coverage-report-action@7f750dd50f5585533321eb7ebc482b936b49a5d4 # v2
        with:
          package-manager: pnpm
